# Learning Tensorflow Basic.No3
# Interactive Sessions

In [1]:
import tensorflow as tf

session = tf.InteractiveSession()

x = tf.constant(list(range(10)))

In [4]:
print x.eval()
session.close()

[0 1 2 3 4 5 6 7 8 9]


In [5]:
import resource
print("{} Kb".format(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss))

96575488 Kb


In [6]:
import numpy as np
session = tf.InteractiveSession()

X = tf.constant(np.eye(10000))
Y = tf.constant(np.random.randn(10000, 300))

In [7]:
print("{} Kb".format(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss))

1696657408 Kb


In [9]:
Z = tf.matmul(X, Y)
Z.eval()

array([[-0.41727062,  0.42811775, -0.49819676, ...,  1.64517399,
         0.63883445,  0.38352422],
       [-0.53723721,  1.50925936,  0.1317333 , ...,  0.6328732 ,
         1.27112644, -0.35004064],
       [ 0.21095896, -1.86426923, -1.6546904 , ..., -1.18401842,
         0.43510582,  0.56010858],
       ..., 
       [ 0.64406927,  0.47943661,  0.01429516, ...,  0.750441  ,
         0.52768843,  2.05282735],
       [-0.43149353,  0.67972542, -0.11367295, ..., -0.73437698,
         0.94177001,  0.96667755],
       [-1.04477208,  0.08682988, -0.47056203, ...,  0.54834894,
        -0.02809983,  0.85309774]])

In [10]:
print("{} Kb".format(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss))

5040865280 Kb


In [11]:
session.close()

In [1]:
import resource
print("{} Kb".format(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss))

42045440 Kb


In [2]:
import tensorflow as tf
import numpy as np
import resource

session = tf.InteractiveSession()
x = tf.constant(np.random.randint(low = 10000000, size=10000000))
print x.eval()
print("{} Kb".format(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss))

[6168226  180911 2588847 ..., 6446709 7795971 6608535]
576573440 Kb


In [3]:
x = tf.to_float(x, name='ToFloat')
print x.eval()
print("{} Kb".format(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss))
session.close()

[ 6168226.   180911.  2588847. ...,  6446709.  7795971.  6608535.]
896798720 Kb


In [1]:
import resource
print("{} Kb".format(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss))

42201088 Kb


In [8]:
from PIL import Image
from io import BytesIO

import tensorflow as tf
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import resource
import numpy as np

with open("MarshOrchid.jpg") as f:
    x = BytesIO(f.read())
im = Image.open(x)
im

<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=3685x5528 at 0x11208C050>

In [9]:
print("{} Kb".format(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss))

1091411968 Kb


In [19]:
x = tf.placeholder("float32", [None, None, 3])#placeholder("type",[dimensions, 해당 dimension column수])

with tf.Session() as session:
    x_data = im
    result = session.run(x, feed_dict={x: im})
    print(result)
    result_gray = tf.image.rgb_to_grayscale(result, name=None)
    result_gray
result_gray = np.squeeze(result_gray)
plt.imshow(result_gray)

[[[ 147.  137.   88.]
  [ 148.  138.   89.]
  [ 148.  138.   89.]
  ..., 
  [ 143.  160.  116.]
  [ 143.  160.  115.]
  [ 143.  160.  115.]]

 [[ 148.  138.   89.]
  [ 148.  138.   89.]
  [ 148.  138.   89.]
  ..., 
  [ 143.  160.  116.]
  [ 142.  159.  115.]
  [ 142.  159.  114.]]

 [[ 148.  138.   89.]
  [ 148.  138.   89.]
  [ 149.  139.   90.]
  ..., 
  [ 143.  160.  116.]
  [ 143.  160.  116.]
  [ 143.  160.  115.]]

 ..., 
 [[  88.  102.   53.]
  [  87.  101.   52.]
  [  86.  100.   51.]
  ..., 
  [ 132.  128.   81.]
  [ 131.  127.   80.]
  [ 130.  128.   80.]]

 [[  87.  101.   52.]
  [  86.  100.   51.]
  [  84.   98.   49.]
  ..., 
  [ 132.  128.   81.]
  [ 132.  128.   81.]
  [ 131.  127.   80.]]

 [[  87.  101.   52.]
  [  85.   99.   50.]
  [  84.   98.   49.]
  ..., 
  [ 134.  127.   81.]
  [ 132.  128.   81.]
  [ 131.  127.   80.]]]


TypeError: Image data can not convert to float

In [3]:
# First, load the image
filename = "MarshOrchid.jpg"
image = mpimg.imread(filename)

plt.imshow(image)
plt.show()
print("{} Kb".format(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss))

531648512 Kb


In [4]:
image_float = tf.image.convert_image_dtype(image, tf.float32, saturate=False, name=None)

In [5]:
print("{} Kb".format(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss))

532430848 Kb
